import { useEffect, useMemo, useState } from "react";

const API = import.meta.env.VITE_API_BASE_URL ?? "http://localhost:5000";

type Employee={id:string;employeeCode:string;fullName:string;reportingManagerId?:string|null};
type TravelRequest={id:string;requestNumber:string;employeeId:string;travelFrom:string;travelTo:string;travelDuration:string;travelMode?:string|null;vehicleType?:string|null;fromLocation?:string|null;toLocation?:string|null;purpose?:string|null;estimatedAmount?:number|null;status:string;managerRemarks?:string|null;financeRemarks?:string|null};
type Claim={id:string;claimNumber:string;employeeId:string;travelRequestId?:string|null;claimDate:string;travelFrom:string;travelTo:string;travelDuration:string;status:string;totalClaimedAmount:number;totalEligibleAmount:number;totalRejectedAmount:number;employeeRemarks?:string|null};
type Line={id:string;expenseClaimId:string;expenseDate:string;expenseType:string;description?:string|null;travelMode?:string|null;vehicleType?:string|null;distanceKm?:number|null;claimedAmount:number;eligibleAmount:number;rejectedAmount:number;validationStatus?:string|null;validationMessage?:string|null;requiresAttachment:boolean;attachmentProvided:boolean};
type Queue={travelRequests:TravelRequest[];claims:Claim[]};

async function api(path:string,init?:RequestInit){const r=await fetch(API+path,init);const body=await r.json().catch(()=>null);if(!r.ok)throw new Error(body?.message??body?.title??body??"Request failed");return body;}

export default function ExpenseEntry({employees}:{employees:Employee[]}){
 const [section,setSection]=useState<"my"|"approvals">("my");
 const [employeeId,setEmployeeId]=useState("");
 const [requests,setRequests]=useState<TravelRequest[]>([]);
 const [claims,setClaims]=useState<Claim[]>([]);
 const [selectedClaim,setSelectedClaim]=useState<{claim:Claim;lines:Line[]}|null>(null);
 const [message,setMessage]=useState(""); const [error,setError]=useState("");

 const selectedEmployee=employees.find(x=>x.id===employeeId);
 const loadMine=async()=>{if(!employeeId)return;try{setError("");const [r,c]=await Promise.all([api("/api/expense/travel-requests?employeeId="+employeeId),api("/api/expense/claims?employeeId="+employeeId)]);setRequests(r);setClaims(c);}catch(e){setError(e instanceof Error?e.message:"Could not load expenses.");}};
 useEffect(()=>{void loadMine();},[employeeId]);

 const createRequest=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{setError("");await api("/api/expense/travel-requests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({employeeId,travelFrom:f.get("travelFrom"),travelTo:f.get("travelTo"),travelMode:f.get("travelMode"),vehicleType:f.get("vehicleType"),fromLocation:f.get("fromLocation"),toLocation:f.get("toLocation"),purpose:f.get("purpose"),estimatedAmount:f.get("estimatedAmount")?Number(f.get("estimatedAmount")):null})});e.currentTarget.reset();setMessage("Travel request created.");await loadMine();}catch(x){setError(x instanceof Error?x.message:"Could not create request.");}};
 const submitRequest=async(id:string)=>{try{setError("");await api("/api/expense/travel-requests/"+id+"/submit",{method:"POST"});setMessage("Travel request submitted to the reporting manager.");await loadMine();}catch(x){setError(x instanceof Error?x.message:"Could not submit request.");}};
 const createClaim=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{setError("");await api("/api/expense/claims",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({employeeId,travelRequestId:f.get("travelRequestId")||null,travelFrom:f.get("travelFrom"),travelTo:f.get("travelTo"),employeeRemarks:f.get("employeeRemarks")||null})});e.currentTarget.reset();setMessage("Expense claim created.");await loadMine();}catch(x){setError(x instanceof Error?x.message:"Could not create claim.");}};
 const openClaim=async(id:string)=>{try{setError("");setSelectedClaim(await api("/api/expense/claims/"+id));}catch(x){setError(x instanceof Error?x.message:"Could not load claim.");}};
 const addLine=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!selectedClaim)return;const f=new FormData(e.currentTarget);try{setError("");await api("/api/expense/claims/"+selectedClaim.claim.id+"/lines",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({expenseDate:f.get("expenseDate"),expenseType:f.get("expenseType"),description:f.get("description")||null,travelMode:f.get("travelMode")||null,vehicleType:f.get("vehicleType")||null,distanceKm:f.get("distanceKm")?Number(f.get("distanceKm")):null,claimedAmount:Number(f.get("claimedAmount"))})});e.currentTarget.reset();setMessage("Expense line added and policy validation applied.");await openClaim(selectedClaim.claim.id);await loadMine();}catch(x){setError(x instanceof Error?x.message:"Could not add line.");}};
 const validate=async()=>{if(!selectedClaim)return;try{setError("");await api("/api/expense/claims/"+selectedClaim.claim.id+"/validate",{method:"POST"});setMessage("Claim revalidated against the effective travel policy.");await openClaim(selectedClaim.claim.id);await loadMine();}catch(x){setError(x instanceof Error?x.message:"Validation failed.");}};
 const submitClaim=async()=>{if(!selectedClaim)return;try{setError("");await api("/api/expense/claims/"+selectedClaim.claim.id+"/submit",{method:"POST"});setMessage("Expense claim submitted to the reporting manager.");await openClaim(selectedClaim.claim.id);await loadMine();}catch(x){setError(x instanceof Error?x.message:"Could not submit claim.");}};
 const upload=async(lineId:string,file:File)=>{if(!selectedClaim)return;try{setError("");const fd=new FormData();fd.append("file",file);fd.append("lineId",lineId);await api("/api/expense/claims/"+selectedClaim.claim.id+"/attachments",{method:"POST",body:fd});setMessage("Receipt uploaded.");await openClaim(selectedClaim.claim.id);}catch(x){setError(x instanceof Error?x.message:"Receipt upload failed.");}};
 return <div className="content">
   <div className="panel expense-toolbar"><div><h2>Expenses & Travel</h2><p className="muted">Create travel requests, enter expense lines, upload receipts and follow the approval status.</p></div><div className="expense-toolbar-actions"><select value={employeeId} onChange={e=>{setEmployeeId(e.target.value);setSelectedClaim(null)}}><option value="">Select employee</option>{employees.map(x=><option value={x.id} key={x.id}>{x.employeeCode} · {x.fullName}</option>)}</select><button type="button" className={section==="my"?"":"secondary-button"} onClick={()=>setSection("my")}>My Expenses</button><button type="button" className={section==="approvals"?"":"secondary-button"} onClick={()=>setSection("approvals")}>Approvals</button></div>{message&&<div className="success">{message}</div>}{error&&<div className="expense-error">{error}</div>}</div>
   {!employeeId&&<div className="panel empty">Select an employee to enter expenses or act on approvals.</div>}
   {employeeId&&section==="my"&&<div className="expense-grid">
     <div className="panel"><h3>New Travel Request</h3><form onSubmit={createRequest} className="expense-form"><input type="date" name="travelFrom" required/><input type="date" name="travelTo" required/><select name="travelMode"><option value="">Travel mode</option><option>Air</option><option>Train</option><option>Overnight Bus</option><option>Own Vehicle</option><option>Local</option></select><select name="vehicleType"><option value="">Vehicle type</option><option>Bike</option><option>Car</option><option>Bus</option></select><input name="fromLocation" placeholder="From location"/><input name="toLocation" placeholder="To location"/><input name="purpose" placeholder="Purpose"/><input type="number" step="0.01" min="0" name="estimatedAmount" placeholder="Estimated amount"/><button type="submit">Create Travel Request</button></form></div>
     <div className="panel"><h3>Travel Requests</h3><div className="table-wrap"><table><thead><tr><th>Request</th><th>Period</th><th>Route</th><th>Status</th><th></th></tr></thead><tbody>{requests.length===0?<tr><td colSpan={5} className="empty">No travel requests.</td></tr>:requests.map(x=><tr key={x.id}><td>{x.requestNumber}</td><td>{x.travelFrom} → {x.travelTo}</td><td>{x.fromLocation||"-"} → {x.toLocation||"-"}</td><td><Status value={x.status}/></td><td>{x.status==="Draft"&&<button type="button" className="link-button" onClick={()=>void submitRequest(x.id)}>Submit</button>}</td></tr>)}</tbody></table></div></div>
     <div className="panel"><h3>New Expense Claim</h3><form onSubmit={createClaim} className="expense-form"><select name="travelRequestId"><option value="">No linked travel request</option>{requests.filter(x=>x.status==="Approved").map(x=><option value={x.id} key={x.id}>{x.requestNumber} · {x.travelFrom} → {x.travelTo}</option>)}</select><input type="date" name="travelFrom" required/><input type="date" name="travelTo" required/><textarea name="employeeRemarks" placeholder="Remarks"/><button type="submit">Create Expense Claim</button></form><p className="muted">For linked claims, the approved travel request controls the allowed period.</p></div>
     <div className="panel"><h3>My Expense Claims</h3><div className="table-wrap"><table><thead><tr><th>Claim</th><th>Period</th><th>Claimed</th><th>Eligible</th><th>Rejected</th><th>Status</th><th></th></tr></thead><tbody>{claims.length===0?<tr><td colSpan={7} className="empty">No expense claims.</td></tr>:claims.map(x=><tr key={x.id}><td>{x.claimNumber}</td><td>{x.travelFrom} → {x.travelTo}</td><td>₹{x.totalClaimedAmount.toFixed(2)}</td><td>₹{x.totalEligibleAmount.toFixed(2)}</td><td>₹{x.totalRejectedAmount.toFixed(2)}</td><td><Status value={x.status}/></td><td><button type="button" className="link-button" onClick={()=>void openClaim(x.id)}>Open</button></td></tr>)}</tbody></table></div></div>
     {selectedClaim&&<div className="panel claim-editor"><div className="claim-head"><div><h3>{selectedClaim.claim.claimNumber}</h3><span>{selectedClaim.claim.travelFrom} → {selectedClaim.claim.travelTo} · <Status value={selectedClaim.claim.status}/></span></div><div className="claim-actions">{selectedClaim.claim.status==="Draft"&&<><button type="button" className="secondary-button" onClick={()=>void validate()}>Revalidate</button><button type="button" onClick={()=>void submitClaim()}>Submit Claim</button></>}</div></div>
       <form onSubmit={addLine} className="expense-form line-form"><input type="date" name="expenseDate" defaultValue={selectedClaim.claim.travelFrom} required/><select name="expenseType" required><option value="">Expense type</option><option>Air</option><option>Train</option><option>Overnight Bus</option><option>Hotel</option><option>Food</option><option>OwnBike</option><option>OwnCar</option><option>LocalBike</option><option>LocalCar</option><option>Petrol</option><option>Other</option></select><input name="description" placeholder="Description"/><select name="travelMode"><option value="">Travel mode</option><option>Air</option><option>Train</option><option>Overnight Bus</option><option>Own Vehicle</option><option>Local</option></select><select name="vehicleType"><option value="">Vehicle</option><option>Bike</option><option>Car</option><option>Bus</option></select><input type="number" step="0.01" min="0" name="distanceKm" placeholder="Distance km"/><input type="number" step="0.01" min="0" name="claimedAmount" placeholder="Claimed amount" required/><button type="submit">Add Expense Line</button></form>
       <div className="table-wrap"><table><thead><tr><th>Date</th><th>Type</th><th>Claimed</th><th>Eligible</th><th>Rejected</th><th>Policy</th><th>Receipt</th></tr></thead><tbody>{selectedClaim.lines.length===0?<tr><td colSpan={7} className="empty">Add your first expense line.</td></tr>:selectedClaim.lines.map(l=><tr key={l.id}><td>{l.expenseDate}</td><td>{l.expenseType}<br/><small>{l.description}</small></td><td>₹{l.claimedAmount.toFixed(2)}</td><td>₹{l.eligibleAmount.toFixed(2)}</td><td>₹{l.rejectedAmount.toFixed(2)}</td><td><span className={l.validationStatus==="Valid"?"valid-badge":"warning-badge"}>{l.validationStatus||"Pending"}</span><br/><small>{l.validationMessage}</small></td><td>{l.requiresAttachment&&!l.attachmentProvided?<label className="receipt-button">Upload<input type="file" accept=".pdf,.jpg,.jpeg,.png,application/pdf,image/jpeg,image/png" onChange={e=>{const file=e.target.files?.[0];if(file)void upload(l.id,file)}}/></label>:l.attachmentProvided?<span className="valid-badge">Attached</span>:<span className="muted">Optional</span>}</td></tr>)}</tbody></table></div>
       <div className="claim-totals"><strong>Claimed ₹{selectedClaim.claim.totalClaimedAmount.toFixed(2)}</strong><strong>Eligible ₹{selectedClaim.claim.totalEligibleAmount.toFixed(2)}</strong><strong>Rejected ₹{selectedClaim.claim.totalRejectedAmount.toFixed(2)}</strong></div>
     </div>}
   </div>}
   {employeeId&&section==="approvals"&&<ApprovalCenter employees={employees} actorId={employeeId} onMessage={setMessage} onError={setError}/>}
 </div>;
}

function ApprovalCenter({employees,actorId,onMessage,onError}:{employees:Employee[];actorId:string;onMessage:(v:string)=>void;onError:(v:string)=>void}){
 const [role,setRole]=useState<"manager"|"finance">("manager"); const [queue,setQueue]=useState<Queue>({travelRequests:[],claims:[]});
 const load=async()=>{try{onError("");setQueue(await api("/api/expense/approval-queue?role="+role+"&employeeId="+actorId));}catch(e){onError(e instanceof Error?e.message:"Could not load approval queue.");}};
 useEffect(()=>{void load()},[role,actorId]);
 const decide=async(type:"travel"|"claim",id:string,approve:boolean)=>{const remarks=window.prompt(approve?"Remarks (optional)":"Reason for rejection");if(!approve&&!remarks)return;try{onError("");const path=type==="travel"?"/api/expense/travel-requests/"+id+"/manager-decision":"/api/expense/claims/"+id+"/manager-decision";const financePath=type==="travel"?"/api/expense/travel-requests/"+id+"/finance-decision":"/api/expense/claims/"+id+"/finance-decision";await api(role==="manager"?path:financePath,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({approve,remarks,approverId:actorId})});onMessage(approve?"Approved successfully.":"Rejected successfully.");await load();}catch(e){onError(e instanceof Error?e.message:"Approval failed.");}};
 const sendBack=async(type:"travel"|"claim",id:string)=>{const remarks=window.prompt("Reason for sending back");if(!remarks)return;try{onError("");const path=type==="travel"?"/api/expense/travel-requests/"+id+"/send-back":"/api/expense/claims/"+id+"/send-back";await api(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({actorEmployeeId:actorId,remarks})});onMessage("Sent back to employee.");await load();}catch(e){onError(e instanceof Error?e.message:"Send-back failed.");}};
 return <div className="approval-grid"><div className="panel"><div className="approval-head"><div><h3>Approval Queue</h3><p className="muted">Review requests assigned to the selected approver.</p></div><select value={role} onChange={e=>setRole(e.target.value as "manager"|"finance")}><option value="manager">Reporting Manager</option><option value="finance">Finance</option></select></div><p className="muted">Actor: {employees.find(x=>x.id===actorId)?.employeeCode??actorId}</p></div>
 <div className="panel"><h3>Travel Requests · {queue.travelRequests.length}</h3><div className="table-wrap"><table><thead><tr><th>Request</th><th>Employee</th><th>Period</th><th>Purpose</th><th>Actions</th></tr></thead><tbody>{queue.travelRequests.map(x=><tr key={x.id}><td>{x.requestNumber}</td><td>{employeeName(x.employeeId,employees)}</td><td>{x.travelFrom} → {x.travelTo}</td><td>{x.purpose||"-"}</td><td><ActionButtons onApprove={()=>void decide("travel",x.id,true)} onReject={()=>void decide("travel",x.id,false)} onSendBack={()=>void sendBack("travel",x.id)}/></td></tr>)}{queue.travelRequests.length===0&&<tr><td colSpan={5} className="empty">No travel requests waiting for this role.</td></tr>}</tbody></table></div></div>
 <div className="panel"><h3>Expense Claims · {queue.claims.length}</h3><div className="table-wrap"><table><thead><tr><th>Claim</th><th>Employee</th><th>Period</th><th>Amounts</th><th>Actions</th></tr></thead><tbody>{queue.claims.map(x=><tr key={x.id}><td>{x.claimNumber}</td><td>{employeeName(x.employeeId,employees)}</td><td>{x.travelFrom} → {x.travelTo}</td><td>₹{x.totalClaimedAmount.toFixed(2)} claimed<br/>₹{x.totalEligibleAmount.toFixed(2)} eligible</td><td><ActionButtons onApprove={()=>void decide("claim",x.id,true)} onReject={()=>void decide("claim",x.id,false)} onSendBack={()=>void sendBack("claim",x.id)}/></td></tr>)}{queue.claims.length===0&&<tr><td colSpan={5} className="empty">No expense claims waiting for this role.</td></tr>}</tbody></table></div></div>
 </div>;
}
function ActionButtons(p:{onApprove:()=>void;onReject:()=>void;onSendBack:()=>void}){return <div className="action-buttons"><button type="button" onClick={p.onApprove}>Approve</button><button type="button" className="secondary-button" onClick={p.onSendBack}>Send Back</button><button type="button" className="danger-button" onClick={p.onReject}>Reject</button></div>}
function employeeName(id:string,employees:Employee[]){const x=employees.find(e=>e.id===id);return x?x.employeeCode+" · "+x.fullName:id}
function Status({value}:{value:string}){return <span className={"status-badge status-"+value.toLowerCase()}>{value}</span>}
